test: 1230688
test2: 88888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.213.81:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.213.81
    port: 6379
    password: 123456
    database: 2
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
